{
 "title": "Wepy OpenMM Data",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Job: $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kinetic Energy (OpenMM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "kJ/mol" }
   ],
   "targets": [
    {
     "expr": "kinetic_energy_kilojoule_per_mole{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Potential Energy (OpenMM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "kJ/mol" }
   ],
   "targets": [
    {
     "expr": "potential_energy_kilojoule_per_mole{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Kinetic Energy (geomm)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "kJ/mol" }
   ],
   "targets": [
    {
     "expr": "geomm_kinetic_energy_kilojoule_per_mole{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Temperature (geomm)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "kelvin" }
   ],
   "targets": [
    {
     "expr": "potential_energy_kilojoule_per_mole{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Box Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "nm^3" }
   ],
   "targets": [
    {
     "expr": "box_volume_nanometer_to_3{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Density",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "density" }
   ],
   "targets": [
    {
     "expr": "density_nil{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Max Force",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kJ/(nm*mol)" }
   ],
   "targets": [
    {
     "expr": "max_force_kilojoule_per__nanometer_by_mole_{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Max Velocity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "nm/ps" }
   ],
   "targets": [
    {
     "expr": "max_velocity_nanometer_per_picosecond{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Radius of Gyration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "radius_of_gyration_nil{job=\"$job\"}"
    }
   ]
  }
 ]
}