{
 "title": "Wepy Simulation",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Job: $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "job" },
  {
   "title": "Segment Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "wepy_mapper_segment_times_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Cycles Completed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wepy_cycle_idx_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Worker Segment Averages",
   "type": "graph",
   "description": "Average of segment times by Worker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (worker_idx) (wepy_mapper_segment_times_seconds{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Big Component Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "wepy_bc_cycle_time_seconds{job=\"$job\"}"
    },
    {
     "expr": "wepy_resampling_cycle_time_seconds{job=\"$job\"}"
    },
    {
     "expr": "wepy_sim_manager_segment_time_seconds{job=\"$job\"}"
    },
    {
     "expr": "wepy_sim_manager_segment_overhead_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Worker Segment Stats across all Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(wepy_mapper_segment_times_seconds{job=\"$job\"})",
     "legendFormat": "Avg. Seg. Time"
    },
    {
     "expr": "max(wepy_mapper_segment_times_seconds{job=\"$job\"})",
     "legendFormat": "Max Seg. Time"
    },
    {
     "expr": "min(wepy_mapper_segment_times_seconds{job=\"$job\"})",
     "legendFormat": "Min Seg. Time"
    },
    {
     "expr": "avg(wepy_mapper_segment_times_seconds{job=\"$job\"}) + stddev(wepy_mapper_segment_times_seconds{job=\"$job\"})",
     "legendFormat": "Std. Dev. +"
    },
    {
     "expr": "avg(wepy_mapper_segment_times_seconds{job=\"$job\"}) - stddev(wepy_mapper_segment_times_seconds{job=\"$job\"})",
     "legendFormat": "Std. Dev. -"
    }
   ]
  },
  {
   "title": "Reporters Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wepy_reporters_size_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Runner Segment Split Times",
   "type": "graph",
   "description": "Aggregated split times for different phases of the runner run segment for individual segments",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(wepy_runner_segment_gen_sim_time_seconds{job=\"$job\"})",
     "legendFormat": "Avg. Seg. Gen Sim Time"
    },
    {
     "expr": "avg(wepy_runner_segment_steps_time_seconds{job=\"$job\"})",
     "legendFormat": "Avg. Seg. Steps Time"
    },
    {
     "expr": "avg(wepy_runner_segment_get_state_time_seconds{job=\"$job\"})",
     "legendFormat": "Avg. Seg. Get State Time"
    },
    {
     "expr": "avg(wepy_runner_segment_run_segment_time_seconds{job=\"$job\"})",
     "legendFormat": "Avg. Seg. run_segment Time"
    },
    {
     "expr": "wepy_runner_precycle_time_seconds{job=\"$job\"}"
    },
    {
     "expr": "wepy_runner_postcycle_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Component Sizes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wepy_sim_manager_size_bytes{job=\"$job\"}"
    },
    {
     "expr": "wepy_walker_single_size_bytes{job=\"$job\"}"
    },
    {
     "expr": "wepy_walker_ensemble_size_bytes{job=\"$job\"}"
    },
    {
     "expr": "wepy_runner_size_bytes{job=\"$job\"}"
    },
    {
     "expr": "wepy_resampler_size_bytes{job=\"$job\"}"
    },
    {
     "expr": "wepy_bc_size_bytes{job=\"$job\"}"
    },
    {
     "expr": "wepy_mapper_size_bytes{job=\"$job\"}"
    },
    {
     "expr": "wepy_sim_manager_size_bytes{job=\"$job\"}"
    },
    {
     "expr": "wepy_reporters_size_bytes{job=\"$job\"}"
    }
   ]
  }
 ]
}